#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# Startups
$HOME/.config/bspwm/autostart.sh


# Set workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          20

bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#61AFEF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


